namespace Tsundoku.Tests.MangaDex;

[TestFixture]
[Parallelizable(scope: ParallelScope.All)]
public class MangaDexDescParseTests
{
    [Test]
    public void ParseDescription_ShouldRemoveAwardInformation()
    {
        string inputDescription = "As an UNLUCKY girl prepares to face her death, an UNDEAD who desperately wants to die appears before her! Vicious, violent and buck naked! An unprecedented picaresque hero appears in Shonen Jump!  \n  \n- Winner of the 2020 Tsugimanga award.";
        string expectedDescription = "As an UNLUCKY girl prepares to face her death, an UNDEAD who desperately wants to die appears before her! Vicious, violent and buck naked! An unprecedented picaresque hero appears in Shonen Jump!";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveBracketedLinks()
    {
        string inputDescription = "Crimes commited using manned combat-androids dubbed \"Katana\" run rampant. In an effort to maintain order, the government has organized the AKCD - \"Anti Katana Crime Division.\" Togusa of the 8th squad of the AKCD, while holding existential doubts as a Human-Katana hybrid, continually casts himself into battle…  \n  \n [Official Korean](https://ridibooks.com/books/845012944)  \n [Official Traditional Chinese](https://www.books.com.tw/products/0010625775)\n\n[Wikipedia](https://ja.wikipedia.org/wiki/-%E3%83%92%E3%83%88%E3%82%AC%E3%82%BF%E3%83%8A-)";
        string expectedDescription = "Crimes commited using manned combat-androids dubbed \"Katana\" run rampant. In an effort to maintain order, the government has organized the AKCD - \"Anti Katana Crime Division.\" Togusa of the 8th squad of the AKCD, while holding existential doubts as a Human-Katana hybrid, continually casts himself into battle…";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldLeaveBasicDescriptionUnchangedBeforeOfficialRelease()
    {
        string inputDescription = "Seth is an apprentice sorcerer from the Pompo Hills. Like all sorcerers, he\u0027s an \u0022infected\u0022, one of the few people having survived an encounter with a Nemesis, those creatures falling from the sky and destroying everything around them. Being immune to them, Seth wants to become a Hunter and fight the Nemesis. But what Seth really wants is to find the source of all Nemesis, the Radiant. Helped by his fellow sorcerers, he will seek the Radiant, under the harsh scrutiny of the Inquisition…\n\n\n---\nOfficial Release:\n- Indonesian release by Elex Media (2021)";
        string expectedDescription = "Seth is an apprentice sorcerer from the Pompo Hills. Like all sorcerers, he\u0027s an \u0022infected\u0022, one of the few people having survived an encounter with a Nemesis, those creatures falling from the sky and destroying everything around them. Being immune to them, Seth wants to become a Hunter and fight the Nemesis. But what Seth really wants is to find the source of all Nemesis, the Radiant. Helped by his fellow sorcerers, he will seek the Radiant, under the harsh scrutiny of the Inquisition…";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveTripleDashBreak()
    {
        string inputDescription = "Workaholic assistant Atobe Arihito fell asleep in his company's bus that was traveling for a vacation. When he awoke he learned he had died due to the bus getting into an accident, and that he had reincarnated into a world of reincarnators - to the Labyrinth Country. To his surprise he was discovered by his slave driving manager, Igarashi Kyouka, who further explains their role in this world.  \nIn Labyrinth Country, Reincarnators are expected to choose a job and form parties to fight against monsters in Labyrinths. \"Valkyrie\" Kyouka had expected Arihito to work with her once again, but he declines due to his knowledge of her demanding nature. As they depart she vows to make him regret not choosing her. And thus starts Arihito's adventure as a \"Rear Guard\".  \n\n\n---";
        string expectedDescription = "Workaholic assistant Atobe Arihito fell asleep in his company's bus that was traveling for a vacation. When he awoke he learned he had died due to the bus getting into an accident, and that he had reincarnated into a world of reincarnators - to the Labyrinth Country. To his surprise he was discovered by his slave driving manager, Igarashi Kyouka, who further explains their role in this world.  \nIn Labyrinth Country, Reincarnators are expected to choose a job and form parties to fight against monsters in Labyrinths. \"Valkyrie\" Kyouka had expected Arihito to work with her once again, but he declines due to his knowledge of her demanding nature. As they depart she vows to make him regret not choosing her. And thus starts Arihito's adventure as a \"Rear Guard\".";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveLinksSurroundedByBreaks()
    {
        string inputDescription = "10 years ago, after \u201Cthe Gate\u201D that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as \u201CHunters\u201D. However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I\u2019m someone who has to risk his life in the lowliest of dungeons, the \u201CWorld\u2019s Weakest\u201D. Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons\u2026 at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!\n\n**Links:**\n\n- Official English Translation [\u003CPocket Comics\u003E](https://www.pocketcomics.com/comic/320) | [\u003CWebNovel\u003E](https://www.webnovel.com/comic/only-i-level-up-(solo-leveling)_15227640605485101) | [\u003CTapas\u003E](https://tapas.io/series/solo-leveling-comic/info)";
        string expectedDescription = "10 years ago, after \u201Cthe Gate\u201D that connected the real world with the monster world opened, some of the ordinary, everyday people received the power to hunt monsters within the Gate. They are known as \u201CHunters\u201D. However, not all Hunters are powerful. My name is Sung Jin-Woo, an E-rank Hunter. I\u2019m someone who has to risk his life in the lowliest of dungeons, the \u201CWorld\u2019s Weakest\u201D. Having no skills whatsoever to display, I barely earned the required money by fighting in low-leveled dungeons\u2026 at least until I found a hidden dungeon with the hardest difficulty within the D-rank dungeons! In the end, as I was accepting death, I suddenly received a strange power, a quest log that only I could see, a secret to leveling up that only I know about! If I trained in accordance with my quests and hunted monsters, my level would rise. Changing from the weakest Hunter to the strongest S-rank Hunter!";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldHandleDoubleBreakWithContentsAndLinks()
    {
        string inputDescription = "King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Beneath the glamorous exterior of a powerful king lurks the shell of man, devoid of purpose and will.\n\nReincarnated into a new world filled with magic and monsters, the king has a second chance to relive his life. Correcting the mistakes of his past will not be his only challenge, however. Underneath the peace and prosperity of the new world is an undercurrent threatening to destroy everything he has worked for, questioning his role and reason for being born again.\n\n\n---\n**Contents:** 1 (Prologue) \u002B 24 (S1) \u002B 30 (S2) \u002B 28 (S3) \u002B 39 (S4) \u002B 49 (S5) = 172 chapters\n- **Season 1:** ch. 0-25\n- **Season 2:** ch. 26-56\n- **Season 3:** ch. 57-85\n- **Season 4:** ch. 86-125\n- **Season 5:** ch. 126-175\n\n---\n\n**Links:**\n- [Official Chinese (Simp) Translation](https://www.kuaikanmanhua.com/web/topic/6884/)\n- [Official Japanese Translation](https://piccoma.com/web/product/19682)\n- [Official Korean Translation](https://page.kakao.com/home?seriesId=53142176)\n- [Official Thai Translation](http://www.comico.in.th/titles/1171)\n- [Official French Translation](https://www.delitoon.com/webtoon/beginning-after-the-end)\n- [Official TBATE Discord Server](https://discord.gg/ZJHAnzF)\n- [TurtleMe Patreon Page](https://www.patreon.com/TurtleMe)";
        string expectedDescription = "King Grey has unrivaled strength, wealth, and prestige in a world governed by martial ability. However, solitude lingers closely behind those with great power. Beneath the glamorous exterior of a powerful king lurks the shell of man, devoid of purpose and will.\n\nReincarnated into a new world filled with magic and monsters, the king has a second chance to relive his life. Correcting the mistakes of his past will not be his only challenge, however. Underneath the peace and prosperity of the new world is an undercurrent threatening to destroy everything he has worked for, questioning his role and reason for being born again.";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldHandleBreakAndLinksInCyrillicText()
    {
        string inputDescription = "Главный герой — трудоголик с большим стажем, он и его босс попадают в аварию, после чего они обнаруживают, что переместились в другой мир. Главный герой не хочет оставаться с начальницей, решая отправиться на приключения в одиночестве. Куда же его приведут эти странствия и встретятся ли они вновь?..   \n\n\n---\n\n**Links:** [Alternate Raw](https://comic-walker.com/contents/detail/KDCW_MF00000068010000_68/)";
        string expectedDescription = "Главный герой — трудоголик с большим стажем, он и его босс попадают в аварию, после чего они обнаруживают, что переместились в другой мир. Главный герой не хочет оставаться с начальницей, решая отправиться на приключения в одиночестве. Куда же его приведут эти странствия и встретятся ли они вновь?..";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveTrailingLinksSection()
    {
        string inputDescription = "Kinoshita Kazuya is a regular college student who was just dumped by his girlfriend for another guy. Feeling down in the dumps, he decides to use an app called Diamond to hire Mizuhara Chizuru, a rental girlfriend, to make himself feel better. From their first meeting, she seems to be the perfect girl for him, but is there more to her than meets the eye? And how will their not quite typical relationship develop?\n\n---\n**Links:**\n\n- Alternative Official English - [K MANGA](https://kmanga.kodansha.com/title/10001/episode/312699) (U.S. Only), [Kodansha](https://kodansha.us/series/rent-a-girlfriend/)";
        string expectedDescription = "Kinoshita Kazuya is a regular college student who was just dumped by his girlfriend for another guy. Feeling down in the dumps, he decides to use an app called Diamond to hire Mizuhara Chizuru, a rental girlfriend, to make himself feel better. From their first meeting, she seems to be the perfect girl for him, but is there more to her than meets the eye? And how will their not quite typical relationship develop?";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldHandleLinksWithCarriageReturns()
    {
        string inputDescription = "Since ancient times, rumors have abounded of man-eating demons lurking in the woods. Because of this, the local townsfolk never venture outside at night. Legend has it that a demon slayer also foams the night, hunting down these bloodthirsty demons.  \r\nEver since the death of his father, Tanjirou has taken it upon himself to support his mother and five siblings. Although their lives may be hardened by tragedy, they've found happiness. But that ephemeral warmth is shattered one day when Tanjirou finds his family slaughtered and the lone survivor, his sister Nezuko, turned into a demon. Adding to this sorrow, a demon hunter named Tomioka Giyuu arrived and was about to finish Nezuko off, but to his surprise she and Tanjiro started to protect each other. Seeing this oddity and Tanjiro's promising fighting skills, Giyuu decides to send them to his old mentor to be trained.  \r\nSo begins Tanjiro's life as a demon hunter, bound on a quest to cure his sister and find the one who murdered his entire family.  \r\n  \r\nMangaPlus: <https://mangaplus.shueisha.co.jp/titles/100009>";
        string expectedDescription = "Since ancient times, rumors have abounded of man-eating demons lurking in the woods. Because of this, the local townsfolk never venture outside at night. Legend has it that a demon slayer also foams the night, hunting down these bloodthirsty demons.  \r\nEver since the death of his father, Tanjirou has taken it upon himself to support his mother and five siblings. Although their lives may be hardened by tragedy, they've found happiness. But that ephemeral warmth is shattered one day when Tanjirou finds his family slaughtered and the lone survivor, his sister Nezuko, turned into a demon. Adding to this sorrow, a demon hunter named Tomioka Giyuu arrived and was about to finish Nezuko off, but to his surprise she and Tanjiro started to protect each other. Seeing this oddity and Tanjiro's promising fighting skills, Giyuu decides to send them to his old mentor to be trained.  \r\nSo begins Tanjiro's life as a demon hunter, bound on a quest to cure his sister and find the one who murdered his entire family.";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveLinkSectionWithExtraUnderscores()
    {
        string inputDescription = "There are six races in this world: human, beast, dragon, elf, dwarf, and demon. Humans are discriminated against and looked down on as the most inferior race. The \"Gathering of Races\" was a party with members from each race gathered to dispel such discrimination, but they also had a hidden purpose. They were ordered by the non-human countries to search for the human \"Master,\" and take it to their own country.\n\nLight, a human boy with the gift \"Infinite Gacha,\" was welcomed into the Gathering of Races as he was suspected of being a Master. But in the end, their investigation showed that Light was not a Master. Just as Light was about to be killed by his teammates, he accidentally stepped on a transfer trap and was teleported to the lowest level of the dungeon.\n\nIn the deepest dungeon, he was attacked by a mythical level 1000 demon. In a desperate situation, Light used \"Infinite Gacha\" repeatedly. Luckily, he draws the SUR level 9999 card \"Mei the Seeker Maid.\" Mei helped Light repel the demons and saved his life.\n\nAfter finally escaping from the crisis, Light decides to take revenge on his former comrades. Mei advises him to remain in the dungeon and use Infinite Gacha to increase his number of trustworthy friends. Light agreed began building up the power necessary to oppose the non-human nations.\n\nThree years later, Light had built the strongest nation in the depths of the dungeon. Once again, he will return to the surface to take revenge on his former comrades and search for the truth that nearly killed him.\n___\n[Alt Official English (US ONLY)](https://kmanga.kodansha.com/title/10040/episode/345702)";
        string expectedDescription = "There are six races in this world: human, beast, dragon, elf, dwarf, and demon. Humans are discriminated against and looked down on as the most inferior race. The \"Gathering of Races\" was a party with members from each race gathered to dispel such discrimination, but they also had a hidden purpose. They were ordered by the non-human countries to search for the human \"Master,\" and take it to their own country.\n\nLight, a human boy with the gift \"Infinite Gacha,\" was welcomed into the Gathering of Races as he was suspected of being a Master. But in the end, their investigation showed that Light was not a Master. Just as Light was about to be killed by his teammates, he accidentally stepped on a transfer trap and was teleported to the lowest level of the dungeon.\n\nIn the deepest dungeon, he was attacked by a mythical level 1000 demon. In a desperate situation, Light used \"Infinite Gacha\" repeatedly. Luckily, he draws the SUR level 9999 card \"Mei the Seeker Maid.\" Mei helped Light repel the demons and saved his life.\n\nAfter finally escaping from the crisis, Light decides to take revenge on his former comrades. Mei advises him to remain in the dungeon and use Infinite Gacha to increase his number of trustworthy friends. Light agreed began building up the power necessary to oppose the non-human nations.\n\nThree years later, Light had built the strongest nation in the depths of the dungeon. Once again, he will return to the surface to take revenge on his former comrades and search for the truth that nearly killed him.";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }

    [Test]
    public void ParseDescription_ShouldRemoveLinkSectionWithExtraLineBreaks()
    {
        string inputDescription = "Guts, known as the Black Swordsman, seeks sanctuary from the demonic forces attracted to him and his woman because of a demonic mark on their necks, and also vengeance against the man who branded him as an unholy sacrifice.\n\nAided only by his titanic strength gained from a harsh childhood lived with mercenaries, a gigantic sword, and an iron prosthetic left hand, Guts must struggle against his bleak destiny, all the while fighting with a rage that might strip him of his humanity.  \n  \n***Won the 6th Osamu Tezuka Cultural Prize Excellence Award in 2002.***\n\n---\n\nNote: Following Miura Kenta's death in 2021, the series has been taken over by Kouji Mori, who supervises the series with art done by Studio Gaga.";
        string expectedDescription = "Guts, known as the Black Swordsman, seeks sanctuary from the demonic forces attracted to him and his woman because of a demonic mark on their necks, and also vengeance against the man who branded him as an unholy sacrifice.\n\nAided only by his titanic strength gained from a harsh childhood lived with mercenaries, a gigantic sword, and an iron prosthetic left hand, Guts must struggle against his bleak destiny, all the while fighting with a rage that might strip him of his humanity.";
        Assert.That(Clients.MangaDex.ParseDescription(inputDescription), Is.EqualTo(expectedDescription));
    }
}
